MODEL:
  META_ARCHITECTURE: "MaskFormer"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 50
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 3
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_N_POINTS: 4
    DEFORMABLE_TRANSFORMER_ENCODER_N_HEADS: 8
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    TRANSFORMER_DECODER_NAME: "HierarchicalDecoder"
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 9
    PRE_NORM: False
    DEEP_SUPERVISION: False
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    DICE_WEIGHT: 5.0
    MASK_WEIGHT: 5.0
    BOUNDARY_WEIGHT: 0.01
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    SIZE_DIVISIBILITY: 32
    USE_FOCAL_LOSS: True
    USE_BOUNDARY_LOSS: True
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: True
DATASETS:
  TRAIN: ("phenobench_train",)
  TEST: ("phenobench_val",)
  TEST_NO_EVAL: ("phenobench_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  MAX_ITER: 30
  CHECKPOINT_PERIOD: 30
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  WEIGHT_DECAY_EMBED: 0.0
  WEIGHT_DECAY_NORM: 0.0
INPUT:
  IMAGE_SIZE: 512
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  RANDOM_FLIP: "horizontal"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
TEST:
  EVAL_PERIOD: 30
  DETECTIONS_PER_IMAGE: 100
  NO_EVAL: False
SEED: -1
RESIZE_AUG: False
VERSION: 2
OUTPUT_DIR: "output/R50_2t_9l_bs4_300ep"